branch-defaults:
  master:
    environment: simplecloj-dev
global:
  application_name: simplecloj
  branch: null
  default_ec2_keyname: terraeast
  default_platform: Docker 1.6.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
