branch-defaults:
  master:
    environment: staging
    group_suffix: null
global:
  application_name: simplecloj
  default_ec2_keyname: mac
  default_platform: Docker 1.6.2
  default_region: us-east-1
  profile: eb-cli
  sc: git

