version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - checkout
      - run: 
          name: Run Application Tests
          command: env
          environment:
          - DATABASE_URL: "jdbc:mysql://localhost/lenny_test?user=root&password=zo8keiPaex"
  test: 
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=zo8keiPaex
        - MYSQL_DATABASE=stagingstore
    steps:
      - run: ls


workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test
