version: 2
jobs:
   build:
     docker:
       - image: circleci/clojure:lein-2.7.1
     steps:
       - checkout
       - run: echo "hello world"
       - run: ls 
       - run: env
       - run: free -m
