defaults: &defaults
  docker:
    - image: circleci/clojure:lein-2.7.1
    - image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=zo8keiPaex
        - MYSQL_DATABASE=lenny_test

version: 2
jobs:
  set_build:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps

  test: 
    <<: *defaults
    steps:
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: 
          name: Run Application Tests
          command: env
          environment:
          - DATABASE_URL: "jdbc:mysql://localhost/lenny_test?user=root&password=zo8keiPaex"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - set_build
      - test:
          requires:
            - set_build
