version: 2
jobs:
   build:
     docker:
       - image: circleci/clojure:lein-2.7.1
     steps:
       - checkout
       - run: lein deps
       - run: lein uberjar
       - store_artifacts:
           path: target/hello-world.jar
           destination: hello-world.jar
